levels:
  WARNING: WARN

formatters:
  HABApp_format:
    format: "[%(asctime)s] [%(name)25s] %(levelname)8s | %(message)s"

  Frontail_format:
    format: "%(asctime)s.%(msecs)03d [%(levelname)-5s] [%(name)-36s] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  # There are several Handlers available:
  #  - logging.handlers.RotatingFileHandler:
  #    Will rotate when the file reaches a certain size (see python logging documentation for args)
  #  - HABApp.config.logging.MidnightRotatingFileHandler:
  #    Will wait until the file reaches a certain size and then will rotate on midnight
  #  - More handlers:
  #    https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler

  HABApp_default:
    class: HABApp.config.logging.MidnightRotatingFileHandler
    filename: "/etc/openhab/habapp/logging/HABApp.log"
    maxBytes: 1_048_576
    backupCount: 3

    formatter: Frontail_format
    level: DEBUG

  EventFile:
    class: HABApp.config.logging.MidnightRotatingFileHandler
    filename: "/etc/openhab/habapp/logging/HABApp_events.log"
    maxBytes: 1_048_576
    backupCount: 3

    formatter: HABApp_format
    level: DEBUG

  MyRuleHandler:
    class: HABApp.config.logging.MidnightRotatingFileHandler
    filename: "/etc/openhab/habapp/logging/MyRule.log" # absolute filename is recommended
    maxBytes: 10_000_000
    backupCount: 3

    formatter: HABApp_format
    level: DEBUG

  AstralHandler:
    class: HABApp.config.logging.MidnightRotatingFileHandler
    filename: "/etc/openhab/habapp/logging/Astral.log"
    maxBytes: 10_000_000
    backupCount: 3

    formatter: HABApp_format
    level: INFO

  ContactSwitchMapping:
    class: HABApp.config.logging.MidnightRotatingFileHandler
    filename: "/etc/openhab/habapp/logging/ContactSwitch.log"
    maxBytes: 10_000_000
    backupCount: 3

    formatter: HABApp_format
    level: INFO

  TinkerforgeHandler:
    class: HABApp.config.logging.MidnightRotatingFileHandler
    filename: "/etc/openhab/habapp/logging/Tinkerforge.log" # absolute filename is recommended
    maxBytes: 10_000_000
    backupCount: 3

    formatter: HABApp_format
    level: INFO

  IkeaHandler:
    class: HABApp.config.logging.MidnightRotatingFileHandler
    filename: "/etc/openhab/habapp/logging/Ikea.log" # absolute filename is recommended
    maxBytes: 10_000_000
    backupCount: 3

    formatter: HABApp_format
    level: INFO

  MqttHandler:
    class: HABApp.config.logging.MidnightRotatingFileHandler
    filename: "/etc/openhab/habapp/logging/Mqtt.log" # absolute filename is recommended
    maxBytes: 10_000_000
    backupCount: 3

    formatter: HABApp_format
    level: INFO

  ThermostatModeHandler:
    class: HABApp.config.logging.MidnightRotatingFileHandler
    filename: "/etc/openhab/habapp/logging/ThermostatMode.log" # absolute filename is recommended
    maxBytes: 10_000_000
    backupCount: 3

  DoorLockModeHandler:
    class: HABApp.config.logging.MidnightRotatingFileHandler
    filename: "/etc/openhab/habapp/logging/DoorLockMode.log" # absolute filename is recommended
    maxBytes: 10_000_000
    backupCount: 3

    formatter: HABApp_format
    level: DEBUG

  MP3PlayerModeHandler:
    class: HABApp.config.logging.MidnightRotatingFileHandler
    filename: "/etc/openhab/habapp/logging/MP3PlayerMode.log" # absolute filename is recommended
    maxBytes: 10_000_000
    backupCount: 3

    formatter: HABApp_format
    level: DEBUG

loggers:
  HABApp:
    level: INFO
    handlers:
      - HABApp_default
    propagate: False

  HABApp.EventBus:
    level: INFO
    handlers:
      - EventFile
    propagate: False

  MyRule:
    level: DEBUG
    handlers:
      - MyRuleHandler # This logger uses the MyRuleHandler
    propagate: False

  Astral:
    level: DEBUG
    handlers:
      - AstralHandler
    propagate: False

  ContactSwitch:
    level: DEBUG
    handlers:
      - ContactSwitchMapping
    propagate: False

  Tinkerforge:
    level: DEBUG
    handlers:
      - TinkerforgeHandler
    propagate: False

  Ikea:
    level: DEBUG
    handlers:
      - IkeaHandler
    propagate: False

  Mqtt:
    level: DEBUG
    handlers:
      - MqttHandler
    propagate: False

  ThermostatMode:
    level: DEBUG
    handlers:
      - ThermostatModeHandler
    propagate: False

  DoorLockMode:
    level: DEBUG
    handlers:
      - DoorLockModeHandler
    propagate: False

  MP3PlayerMode:
    level: DEBUG
    handlers:
      - MP3PlayerModeHandler
    propagate: False
