@startuml lights
(*) --> "key press"

partition Tinkerforge #lightgreen {

  partition io16 #green {
    "key press" --> "detect keys" #olive
  }

  partition out4 #green {
  }

  partition brick #green {
     "detect keys" --> "send signal" #olive
  }
}

partition raspi #pink {

  partition habapp #red {
    "send signal" --> tinkerforge_oh_.py #purple
  }

  partition OH3 #red {
    tinkerforge_oh_.py --> "set item keypress (*_Short/_Long)" #orchid
    "set item keypress (*_Short/_Long)" -> "gSchalter_Short/_Long"  #lightcoral
    "gSchalter_Short/_Long" --> switch2light_mapping.py #purple
    switch2light_mapping.py --> "set item light" #orchid
    "set item light" --> light_follow.py #purple
    light_follow.py --> "set item light"
    "set item light" --> tinkerforge_oh_.py
  }

  partition habapp #red {
    "set item light" --> ikea.py #purple
  }

}

partition "Philips Hue" #lightyellow {
  partition HueApp #yellow {
    "set item light" --> "set hue light"
  }
}

partition volumio #lightblue {
  partition mosquitto #blue {
    ikea.py -> "set mqtt topic" #indigo
  }

  partition zigbee2mqtt #blue {
    "set mqtt topic" -> "set mqtt light" #indigo
  }
}
partition out4 #green {
  tinkerforge_oh_.py --> "set light" #olive
}

"set mqtt light" --> (*)
"set hue light" --> (*)
"set light" --> (*)
@enduml
