@startuml basic_setup
legend top left
    |Color| Type |
    |<#LightGreen> LightGreen | Tinkerforge HW|
    |<#Green> Green | bricklet or brick|
    |<#Olive> Olive | activity on tinkerforge|

    |<#Pink> Pink | RaspberryPi HW|
    |<#Red> Red | Process on RaspberryPi|
    |<#Orchid> Orchid | activity on RaspberryPi|
    |<#Purple> Purple | group changes on RaspberryPi|
    |<#LightCoral> LightCoral | scripty run on RaspberryPi|

    |<#Aqua> Aqua | homematic-raspi HW|
    |<#SpringGreen> SpringGreen | activity on homematic-raspi HW|

    |<#LightYellow> LightYellow | cloud / mobile device|
    |<#Yellow> Yellow | App running on mobile device|

    |<#LightBlue> LightBlue | MQTT|
    |<#Blue> Blue | App running on MQTT|
endlegend

package tinkerforge #LightCyan {
  node "Tinkerforge" #LightGreen {
    component brick #Green {
    }
    component io16 #Green {
    }
    component out4 #Green {
    }

    port USB as usb
    interface brickd #Green

    brick - brickd
    brick - usb

    brick --> io16
    brick --> out4
  }
  node bricklet_io16{
  }
  node bricklet_out4{
  }

  bricklet_io16 --> usb
  bricklet_out4 --> usb
}

node raspi #Pink {
  component habapp #Red {
  }
  component OH3 as oh #Red {
  }
  component grafana #Red {
  }
  component influxDB #Red {
  }

  interface OH_Rest_API as oh_rest_if #Red
  oh -up- oh_rest_if

 interface influxDB as influxDB_if #Red
 influxDB -up- influxDB_if

  habapp ..> oh_rest_if : use
  oh ..> influxDB_if : use
  grafana ..> influxDB_if : use
}

package MQTT {
  node volumio #LightBlue {
    component zigbee2mqtt #Blue {
    }
    component mosquitto #Blue {
    }

    port zigbee #Blue
    interface MQTT as mqtt #Blue

    mosquitto -left- mqtt
    zigbee2mqtt - zigbee
    zigbee2mqtt ..> mqtt
  }
  node IKEA_lamp{
  }
  node IKEA_motion_detect{
  }
  node IKEA_remote{
  }

  IKEA_lamp --> zigbee
  IKEA_motion_detect --> zigbee
  IKEA_remote --> zigbee
}

package homematic_ip {
  node homematic-raspi #Aqua{
    component CCU3 #SpringGreen{
    }
    interface homematic as homematic_if #SpringGreen
    port "RPI-RF-MOD" as hmip_rf_if

    CCU3 - homematic_if
    CCU3 - hmip_rf_if
  }
  node hmip_blind {
  }
  node hmip_dimmer {
  }
  node hmip_door_window {
  }
  node hmip_lock {
  }
  node hmip_motion_detect {
  }
  node hmip_mp3 {
  }
  node hmip_plug {
  }
  node hmip_ring_detect {
  }
  node hmip_thermostat {
  }

  hmip_blind --> hmip_rf_if
  hmip_dimmer --> hmip_rf_if
  hmip_door_window --> hmip_rf_if
  hmip_lock --> hmip_rf_if
  hmip_motion_detect --> hmip_rf_if
  hmip_mp3 --> hmip_rf_if
  hmip_plug --> hmip_rf_if
  hmip_ring_detect --> hmip_rf_if
  hmip_thermostat --> hmip_rf_if
}

package cloud {
  node "Alexa" #LightYellow {
    component alexa #Yellow
  }
  node "Bosch" #LightYellow {
    component BoschConnectApp as boschConnectApp #Yellow
    component boschIndegoApp as boschIndegoApp #Yellow
  }
  node "Brennenstuhl" #LightYellow {
    component brennenstuhl_App as brennenstuhlApp #Yellow
  }
  node "Google Assistent" #LightYellow {
    component googleassistent as google #Yellow
  }
  node "Merros" #LightYellow {
    component merros_App as merrosApp #Yellow
  }
  node "Mobile" #LightYellow {
    component openHAB_App as ohApp #Yellow
    component HabPanel as habpanel #Yellow
  }
  node "Philips Hue" #LightYellow {
    component HueApp as hueApp #Yellow
  }

  cloud myOpenhab #sienna {
    component myopenhab #brown
    interface myOH_Rest_API as myOH_Rest_if #brown
    myopenhab -up- myOH_Rest_if
  }

  cloud publicCloud #sienna {
    component boschConnectCloud #brown
    interface boschConnectCloud_Rest_API as boschConnectCloud_if #brown
    boschConnectCloud -up- boschConnectCloud_if

    component boschIndegoCloud #brown
    interface boschIndegoCloud_Rest_API as boschIndegoCloud_if #brown
    boschIndegoCloud -up- boschIndegoCloud_if

    component brennenstuhlCloud #brown
    interface brennenstuhlCloud_Rest_API as brennenstuhlCloud_if #brown
    brennenstuhlCloud -up- brennenstuhlCloud_if

    component hueCloud #brown
    interface hueCloud_Rest_API as hueCloud_if #brown
    hueCloud -up- hueCloud_if

    component merrosCloud #brown
    interface merrosCloud_Rest_API as merrosCloud_if #brown
    merrosCloud -up- merrosCloud_if
  }

}

package hue {
  node "Hue" #gold{
    component HueBridge as hueBridge #orange

    interface HueBridge_If #orange

    port zigbeeHue

    hueBridge -left- HueBridge_If
    hueBridge - zigbeeHue

    hueApp ..> HueBridge_If : use
  }
  package zigbee_hue {
      node hue_light {
      }
      node hue_motion_sensor {
      }
      node hue_plug {
      }
      hue_light --> zigbeeHue
      hue_motion_sensor --> zigbeeHue
      hue_plug --> zigbeeHue
  }

  package zigbee_osram {
      node osram_light {
      }
      node osram_plug {
      }
      osram_light --> zigbeeHue
      osram_plug --> zigbeeHue
  }

  package zigbee_paulmann {
      node paulmann_light {
      }
      paulmann_light --> zigbeeHue
  }
}

alexa ..> myOH_Rest_if : use
alexa ..> hueCloud_if : use

boschConnectApp ..> boschConnectCloud_if : use
boschIndegoCloud ..> myOH_Rest_if : use

boschConnectCloud ..> myOH_Rest_if : use
boschIndegoApp ..> boschIndegoCloud_if : use

brennenstuhlCloud ..> myOH_Rest_if : use
brennenstuhlApp ..> brennenstuhlCloud_if : use

google ..> myOH_Rest_if : use
google ..> hueCloud_if : use

habapp ..> mqtt : use
habapp ..> brickd : use

habpanel ..> oh_rest_if : use
habpanel ..> myOH_Rest_if : use

hueApp ..> hueCloud_if : use
hueBridge ..> oh_rest_if : use
hueCloud ..> myOH_Rest_if : use

merrosCloud ..> myOH_Rest_if : use
merrosApp ..> merrosCloud_if : use

myopenhab ..> oh_rest_if : use

ohApp ..> myOH_Rest_if : use
ohApp ..> oh_rest_if : use

oh ..> homematic_if : use
oh ..> HueBridge_If : use
@enduml
